--COMO ROOT CREAMOS LA BBDD Y EL USUARIO Y LE DAMOS LOS PRIVILEGIOS NECESARIOS

--CREAMOS LA BBDD 

CREATE DATABASE biblioteca
	CHARACTER SET utf8 COLLATE utf8_spanish_ci;
	
--CREAMOS EL USUARIO

DROP USER sergio;
CREATE USER sergio IDENTIFIED BY 'sergio';

--DAMOS LOS TODOS LOS PERMISOS EN LA NUEVA BBDD PARA EL USUARIO CREADO

grant all privileges on biblioteca.* to 'sergio'@'%' identified by 'damuser';
grant all privileges on biblioteca.* to 'sergop'@'localhost' identified by 'sergio';
flush privileges;

--YA COMO USUARIO CREAMOS LAS TABLAS Y LA POBLAMOS DE DATOS

DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS LIBROS;
DROP TABLE IF EXISTS PRESTAMOS;

CREATE TABLE CLIENTE(
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(30) NOT NULL,
	apellido VARCHAR(30) NOT NULL
);

CREATE TABLE LIBROS(
	id INT AUTO_INCREMENT PRIMARY KEY,
	isbn INT NOT NULL,
	titulo VARCHAR(30) NOT NULL,
	autor VARCHAR(30) NOT NULL
);

CREATE TABLE PRESTAMOS(
	CLIENTE INT,
	LIBRO INT,
	FECHAENTREGA DATE,
	FECHARECOGIDA DATE,
	PRIMARY KEY(CLIENTE,LIBRO),
	FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(id),
	FOREIGN KEY(LIBRO) REFERENCES LIBROS(id)
);

--INSERTAMOS DATOS EN LAS TABLAS

INSERT INTO CLIENTE VALUES(
	NULL,
	'SERGIO',
	'PEINADO'
);
INSERT INTO CLIENTE VALUES(
	NULL,
	'JUAN',
	'CASAS'
);
INSERT INTO CLIENTE VALUES(
	NULL,
	'RIGOBERTO',
	'DE LAS TORRES'
);
INSERT INTO LIBROS VALUES(
	NULL,
	16546,
	'ELMINSTER LA FORJA DE UN MAGO',
	'ED GREENWOOD'
);
INSERT INTO LIBROS VALUES(
	NULL,
	15889,
	'LA FABRICA CREATOR',
	'PATRICIA GARCIA-ROJO'
);
INSERT INTO LIBROS VALUES(
	NULL,
	85953,
	'FRAI PERICO Y SU BORRICO',
	'JUAN MUÑOZ'
);
